#pragma once

#include "../../Utils/Utils.h"

inline const char *CurrencyList[]           = { OBFUSCATE("GemsCurrency"),
                                                OBFUSCATE("Coins"),
                                                OBFUSCATE("ClanSilver"),
                                                OBFUSCATE("ClanLootBoxPoints"),
                                                OBFUSCATE("Coupons"),
                                                OBFUSCATE("PixelPassCurrency"),
                                                OBFUSCATE("RouletteAdsCurrency"),
                                                OBFUSCATE("RouletteAdsSpin"),
                                                OBFUSCATE("PixelBucks"),
                                                OBFUSCATE("BattlePassCurrency"),
                                                OBFUSCATE("CurrencyCompetitionTier1"),
                                                OBFUSCATE("CurrencyCompetitionTier2"),
                                                OBFUSCATE("KeySmallChest"),
                                                OBFUSCATE("KeyEventChest"),
                                                OBFUSCATE("KeyBigChest"),
                                                OBFUSCATE("EventChestsSuperSpin"),
                                                OBFUSCATE("EventRouletteSuperSpin"),
                                                OBFUSCATE("EventRouletteSuperSpin"),
                                                OBFUSCATE("Exp"),
                                                OBFUSCATE("TankKeys"),
                                                OBFUSCATE("PixelPassExp"),
                                                OBFUSCATE("clan_building_black_market_point"),
                                                OBFUSCATE("MainModeSlotTokens"),
                                                OBFUSCATE("SmallChest"),
                                                OBFUSCATE("BigChest"),
                                                OBFUSCATE("EventChest"),
                                                OBFUSCATE("MegaChest") };

inline std::vector<std::string> WeaponNames = {
    "FirstPistol",
    "FirstShotgun",
    "UziWeapon",
    "Revolver",
    "Machingun",
    "MinersWeapon",
    "AK47",
    "Knife",
    "m16",
    "Eagle 1",
    "SPAS",
    "FAMAS",
    "Glock",
    "Shovel",
    "Hammer",
    "Beretta",
    "IronSword",
    "SteelAxe",
    "WoodenBow",
    "Chainsaw 2",
    "SteelCrossbow",
    "Hammer 2",
    "Mace 2",
    "Staff 2",
    "DoubleShotgun",
    "AlienGun",
    "m16_2",
    "Tree",
    "Fire_Axe",
    "SVD",
    "Barrett_2",
    "Uzi2",
    "Hunter_Rifle",
    "Bazooka",
    "railgun",
    "tesla",
    "grenade_launcher",
    "grenade_launcher2",
    "Bazooka_3",
    "GravityGun",
    "AUG",
    "katana_3",
    "bigbuddy",
    "Mauser",
    "Shmaiser",
    "Tompson",
    "Tompson_2",
    "basscannon",
    "SparklyBlaster",
    "CherryGun",
    "AK74",
    "FreezeGun",
    "3pl_Shotgun_3",
    "flowerpower_3",
    "Revolver4",
    "Scythe_3",
    "plazma_3",
    "plazma_pistol_2",
    "plazma_pistol_3",
    "Razer_3",
    "Flamethrower_3",
    "FreezeGun_0",
    "Minigun_3",
    "Barret_3",
    "LightSword_3",
    "Sword_2_3",
    "Staff 3",
    "DragonGun",
    "Bow_3",
    "Bazooka_2_3",
    "m79_3",
    "Red_Stone_3",
    "XM8_1",
    "PumpkinGun_1",
    "TwoBolters",
    "RayMinigun",
    "SignalPistol",
    "AutoShotgun",
    "TwoRevolvers",
    "SnowballGun",
    "SnowballMachingun",
    "HeavyShotgun",
    "Solar_Ray",
    "Water_Pistol",
    "Solar_Power_Cannon",
    "Water_Rifle",
    "Needle_Throw",
    "Valentine_Shotgun",
    "Carrot_Sword",
    "Easter_Bazooka",
    "RailRevolverBuy",
    "Assault_Machine_GunBuy",
    "Impulse_Sniper_RifleBuy",
    "Autoaim_RocketlauncherBuy",
    "PX-3000",
    "Sunrise",
    "Bastion",
    "DualHawks",
    "StormHammer",
    "Badcode_gun",
    "ElectroBlastRifle",
    "PlasmaShotgun",
    "Devostator",
    "Dark_Matter_Generator",
    "Hydra",
    "TacticalBow",
    "FutureRifle",
    "RapidFireRifle",
    "DualUzi",
    "LaserDiscThower",
    "Tesla_Cannon",
    "Photon_Pistol",
    "Fire_orb",
    "Hand_dragon",
    "Alligator",
    "Hippo",
    "Alien_Cannon",
    "Alien_Laser_Pistol",
    "Dater_Flowers",
    "Dater_DJ",
    "Dater_Arms",
    "Dater_Bow",
    "FriendsUzi",
    "Alien_rifle",
    "VACUUMIZER",
    "Fireworks_Launcher",
    "Shotgun_Pistol",
    "Range_Rifle",
    "Pit_Bull",
    "Tiger_gun",
    "Balloon_Cannon",
    "Mech_heavy_rifle",
    "Shuriken_Thrower",
    "BASIC_FLAMETHROWER",
    "snowball",
    "MysticOreEmitter",
    "Laser_Crossbow",
    "Nutcracker",
    "SPACE_RIFLE",
    "Icicle_Generator",
    "PORTABLE_DEATH_MOON",
    "Candy_Baton",
    "Hockey_stick",
    "Space_blaster",
    "mp5_gold_gift",
    "Dynamite_Gun_1",
    "Dual_shotguns_1",
    "Antihero_Rifle_1",
    "HarpoonGun_1",
    "Red_twins_pistols_1",
    "Toxic_sniper_rifle_1",
    "NuclearRevolver_1",
    "NAIL_MINIGUN_1",
    "DUAL_MACHETE_1",
    "Fighter_1",
    "Gas_spreader",
    "LaserBouncer_1",
    "magicbook_fireball",
    "magicbook_frostbeam",
    "magicbook_thunder",
    "TurboPistols_1",
    "Laser_Bow_1",
    "loud_piggy",
    "Trapper_1",
    "chainsaw_sword_1",
    "dark_star",
    "toy_bomber",
    "zombie_head",
    "mr_squido",
    "RocketCrossbow",
    "spark_shark",
    "power_claw",
    "zombie_slayer",
    "AcidCannon",
    "frank_sheepone",
    "Ghost_Lantern",
    "Semiauto_sniper",
    "Chain_electro_cannon",
    "Barier_Generator",
    "Demoman",
    "charge_rifle",
    "minigun_pistol",
    "bad_doctor_1",
    "dual_laser_blasters",
    "toxic_bane",
    "Charge_Cannon",
    "Heavy_Shocker",
    "ruler_sword_1",
    "pencil_thrower_1",
    "napalm_cannon",
    "sword_of_shadows",
    "dracula",
    "xmas_destroyer",
    "santa_sword",
    "snow_storm",
    "heavy_gifter",
    "bell_revolver",
    "elfs_revenge",
    "photon_sniper_rifle",
    "subzero",
    "mercenary",
    "laser_spear",
    "nunchuks",
    "double_dragon",
    "magicbook_love",
    "casanova",
    "romeo_and_juliette",
    "Q_grenade_launcher",
    "Q_machine_gun",
    "Q_electrogun",
    "Q_railgun",
    "Q_rocket_launcher",
    "Q_shotgun",
    "Q_plasma_gun",
    "Q_chopper",
    "Q_BFG",
    "Blade_of_Justice",
    "lab_eight_barrel_shotgun",
    "Tactical_tomahawk",
    "Masterpiece_musket",
    "Executioner",
    "Serious_argument",
    "lab_piranha",
    "lab_oneshot",
    "lab_machinegun",
    "lab_combatyoyo",
    "lab_orbital_pistol",
    "Defender_of_the_law",
    "fidget_thrower",
    "festive_bazooka",
    "thunderer",
    "bomber_slingshot",
    "future_sniper_rifle",
    "beast",
    "invader",
    "core_sword",
    "hedgehog",
    "third_eye",
    "eraser",
    "excalibur",
    "poseidon_trident",
    "reaper",
    "void_ray_rifle",
    "black_mamba",
    "chip_sword",
    "vampire_hunter",
    "mountain_wolf",
    "hurricane",
    "dino_slayer",
    "soulstone",
    "electrosphere",
    "prototype_s",
    "frozen_dragon",
    "special_agent",
    "Power_Fists",
    "VerticalShotgun",
    "astral_bow",
    "zeus_chain_ sword",
    "music_lover",
    "veteran",
    "mini_alien_spaceship",
    "flag_keeper",
    "leaders_sword",
    "last_christmas",
    "laser_assistant",
    "dual_cryo_pistols",
    "automatic_decorator",
    "elder_force_saber",
    "Champion_Mercenary",
    "champion_peacemaker",
    "adamant_laser_cannon",
    "Adamant_Revolver",
    "adamant_spear",
    "champion_electric_arc",
    "adamant_sniper_rifle",
    "Anti-Champion_Rifle",
    "Champion_Solar_Cannon",
    "Adamant_Bomber",
    "sharp_snowflake",
    "little_cthulhu",
    "magicbook_curse_spell",
    "airblade_spell",
    "magicbook_poison_spell",
    "magicbook_earth_spikes_spell",
    "magicbook_shadow_spell",
    "Dragon_King",
    "angry_pumpkin",
    "Steam_Knuckes",
    "electro_blast_pistol",
    "wyvern_sniper",
    "hero",
    "sly_avenger",
    "bright_reflector",
    "sakura",
    "deadly_beat",
    "killer_whale",
    "renegade",
    "demon_sword",
    "bolters2",
    "Stormtrooper_Exoskeleton",
    "Sniper_Exoskeleton",
    "demolition_exosceleton",
    "hitman_exoskeleton",
    "berserk_exoskeleton",
    "engineer_exoskeleton",
    "death_claws",
    "Eva",
    "space_desinsector",
    "mega_gun",
    "laser_revolver",
    "Sword_and_Shield",
    "last_samurai",
    "manga_gun",
    "anime_schtye",
    "nitrogen_spreader",
    "future_police_rifle",
    "stakegun",
    "alive_blaster",
    "plasma_cutter",
    "good_doctor",
    "devastator",
    "supercharged_rifle",
    "archangel",
    "manticore",
    "soul_thief",
    "multitaskers",
    "yin_yang",
    "last_hope",
    "Jet_hammer",
    "energy_drill",
    "Spender",
    "graviton",
    "acid_pistol",
    "Rhino",
    "antique_pistol",
    "lava_thrower",
    "Inventors_Rifle",
    "vandals",
    "revolver_sniper_rifle",
    "captain",
    "void_energy_pistol",
    "destruction_system",
    "circus_cannon",
    "military_grenade_launcher",
    "cyborg_hands",
    "ritual_blade",
    "tactical_rifle",
    "sparkling_eel",
    "alien_sniper_rifle",
    "neutralizer",
    "bone_sniper_rifle",
    "prehistoric_shotgun",
    "shamans_bow",
    "poison_darts",
    "primal_beast",
    "eye_of_ra",
    "gym_rifle",
    "bone_crusher",
    "soda_launcher",
    "rocket_launcher",
    "royale_fighter",
    "royale_revolver",
    "royale_sniper_rifle",
    "royale_ashbringer",
    "dagger_shovels",
    "worker_shovel",
    "sniper_shovel",
    "gold_shovel",
    "jet_shovel",
    "shover_laser",
    "monster_shovel",
    "penilizer",
    "fan_revolver",
    "football_cannon",
    "shovel_axe",
    "cursed_pirate",
    "Viking",
    "gladiator",
    "heart_of_volcano",
    "shovel_not_a_shovel",
    "chainsaw_shovel",
    "clan_legend_shovel",
    "shovel_road_sign",
    "cactus_shovel",
    "toy_hammer",
    "igniter",
    "infiltrator",
    "warmaster",
    "combat_slinger",
    "paintball_rifle",
    "energy_rings_exoskeleton",
    "particle_accelerator",
    "RitualRevolvers",
    "magicbook_Spell_of_Bats",
    "deadmans_rifle",
    "Witchunter",
    "industrial_nailer",
    "trick_and_treat",
    "ghost_launcher",
    "poisonous_vine",
    "johnny_p",
    "witch_broom",
    "cyber_slicer",
    "ricochet_rifle",
    "cyber_revolver",
    "neon_lighting",
    "quadruple_death",
    "cops_shovel",
    "cyber_shovel",
    "rocket_hand",
    "cyber_laser",
    "scull_crossbow",
    "shovel_hell",
    "sniper_cyber_module",
    "cops_club",
    "ultimatum",
    "lamp_revolver",
    "drum_rifle",
    "bp_flamethrower",
    "hand_gatling",
    "steamer",
    "gold_digger",
    "bow_of_spirit",
    "tomahawk_shovel",
    "sherif_shovel",
    "miner_shovel",
    "corn_launcher",
    "pie_thrower",
    "triple_musket",
    "demolition_gun",
    "ecco_hunter",
    "like_throver",
    "photo_gun",
    "liquid_fire",
    "electric_vortex",
    "cursed_staff",
    "blinder",
    "peppermint_guardians",
    "freon_gun",
    "shovel_ice",
    "frostomat",
    "frosty_railgun",
    "winter_staff",
    "ice_spiker",
    "shovel_peppermint",
    "total_annihilator",
    "torpedo_launcher",
    "sawed_off_shotguns",
    "gauss_machine_gun",
    "ultra_beam",
    "sock_bomber",
    "energy_assault_rifle",
    "shovel_alien_ice",
    "shovel_ice_skate",
    "futuristic_minigun",
    "sniper_ice",
    "gloves_of_power",
    "space_redeemer",
    "snow_blaster",
    "alien_bounser",
    "alien_shuriken",
    "spruce_pistols",
    "christmas_spirit",
    "ice_lightning",
    "ice_generator",
    "icecream_pistol",
    "whip_with_cake",
    "festive_guitar",
    "evil_snowman",
    "gangerbread_homezooka",
    "portable_gift_factory",
    "saturn",
    "venus_n_mercury",
    "Asteroid",
    "comet_sniper_rifle",
    "meteor_shower",
    "neclaces_ice_king",
    "Ice_Paws",
    "frozen_lich_bow",
    "gift_stitcher",
    "ice_king_anger",
    "gifted_revolvers",
    "yetti_spirit",
    "bambo",
    "new_year_defender",
    "candy_axe",
    "cold_silence",
    "proton_freezer",
    "coldstarter",
    "cyber_machinegun",
    "simple_cybergun",
    "shock",
    "cyber_sniper",
    "simple_cyberlauncher",
    "simple_acid_spray",
    "spec_ops_backup",
    "pixel_cola_refresher",
    "warden",
    "instigator",
    "storm",
    "semi_auto_shotgun",
    "stinger_3000",
    "airstrike_laptop",
    "deadly_digital_system",
    "night_hunter",
    "spec_ops_pistol",
    "tactical_knife",
    "hand_minigun",
    "heavy_sniper_rifle",
    "armadillo",
    "police_zapper",
    "temple_guardian",
    "healing_carp",
    "moon_halberd",
    "magic_primary",
    "magic_backup",
    "magic_melee",
    "magic_special",
    "magic_sniper",
    "royale_alpenstock",
    "agent_valentine",
    "lovebirds",
    "Serenade",
    "heartbreakers",
    "Succubus",
    "postman",
    "harpy",
    "runic_hammer",
    "blade_rifle",
    "arahna_bite",
    "medusa",
    "bigb_oven",
    "mr_mixer",
    "cookie_minigun",
    "magic_blades",
    "alchemic_staff",
    "rune_shovel",
    "Ðüyclops_shovel",
    "system_admin",
    "flash_drive",
    "disconnector",
    "network_streamer",
    "ð░ntivirus",
    "big_data",
    "cyclops_siling",
    "rainbow_dispenser",
    "rainbow_destroyer",
    "mister_l",
    "adamant_claws",
    "hypersound_uzi",
    "double_gum",
    "black_hole",
    "space_shovel",
    "heroic_shovel",
    "protector_of_peace",
    "portalius_wrath",
    "chipping_whip",
    "portalium_rifle",
    "nuclear_rifle",
    "deadly_umbrella",
    "big_bang_revolver",
    "acid_shotgun",
    "batohawk",
    "combat_gautlent",
    "spider_sense",
    "werewolf",
    "sharp_flame",
    "charged_injector",
    "garbage_rifle",
    "firefighter",
    "huge_boy",
    "fireman_shovel",
    "fatal_melter",
    "dual_anger",
    "brutal_thinner",
    "liquidator_z1",
    "eliminator_z2",
    "pursuer_z3",
    "pixelgun_old",
    "plastic_shovel",
    "balloon_shovel",
    "block_rifle",
    "block_shotgun",
    "block_flamethrower",
    "plastic_rifle",
    "plastic_bazooka",
    "plastic_carabin",
    "cloud_launcher",
    "sucker_gun",
    "witch_doctor",
    "portal_cannon",
    "healing_staff",
    "laser_ray_rifle",
    "clockwork_cannon",
    "transformed_blaster",
    "transformed_machinegun",
    "witch_cauldron",
    "combat_darts",
    "throwing_spears",
    "alloha_boom",
    "professional_bow",
    "artifact",
    "ouroboros",
    "keen_courier",
    "uncertainty_emitter",
    "camp_leader_rifle",
    "knife_and_compass",
    "super_loudspeaker",
    "raccoon_with_trumpet",
    "butterfly_net_shovel",
    "guitar_shovel",
    "werewolf_paws",
    "ice_cream_thrower",
    "water_juice_cannon",
    "pop_soda",
    "pyro_1116",
    "sparkling_hydra",
    "tiny_resizer",
    "pawn_cannon",
    "horse_axe",
    "battle_rook",
    "inevitability",
    "chess_board_shovel",
    "royal_shovel",
    "checkmate",
    "proud_eagle",
    "sly_wolf",
    "brave_lion",
    "offensive_catapult",
    "battle_horn",
    "sharp_ring",
    "ornate_bagpipes",
    "pew_pew_rifle",
    "pixel_stream_sword",
    "tube_backpack",
    "supershot_rifle",
    "hyper_mega_cannon",
    "digital_sunrise",
    "lasercycler",
    "wave_pulser",
    "arcade_rifle",
    "arcade_flamethrower",
    "fatality_hook",
    "fireball_gauntlets",
    "anubis",
    "duck_hunter",
    "disc_battle_station",
    "pixel_shovel",
    "holy_shotgun",
    "aspen_spear",
    "dual_hunter_crossbows",
    "plague_purifier",
    "lives_oppressor",
    "sword_of_silence",
    "gravestone_shovel",
    "hot_greetings",
    "cooking_totem",
    "spiritual_rifle",
    "storm_all_seas",
    "huge_anchor_shovel",
    "hard_corn",
    "chef_fork_shovel",
    "lancelot",
    "galahad",
    "percival_n_lamorak",
    "mordred",
    "morgana",
    "bediver",
    "neutron_pulsator",
    "clapper_gun",
    "royal_marryer",
    "snowqueen_wand",
    "heroic_epee",
    "ice_club",
    "last_squeak",
    "fierce_pack",
    "mouse_scepter",
    "ice_chaser",
    "sneaky_revolver",
    "coal_frightener",
    "enchanted_butler_shovel",
    "golden_bros",
    "gangsta_shield",
    "double_cashback",
    "luxury_beats",
    "sniper_dude",
    "gems_power",
    "spirit_staff",
    "offensive_fireworks",
    "sharp_fans",
    "river_dragon",
    "explosive_lemonade",
    "stick_gong_shovel",
    "fire_spirit",
    "thunder_storm",
    "water_blades",
    "deadly_stings",
    "dragon_bite",
    "ancient_scroll",
    "potato_implant",
    "ai_pistol",
    "super_drill",
    "meteorite_fighter",
    "gravitator",
    "predatory_bush_shovel",
    "zap_blaster",
    "pew_blaster",
    "boom_blaster",
    "psionic_spores",
    "poisonous_grasshopper",
    "shrimposaur",
    "desert_fighter",
    "egg_colorizer",
    "hocus_pocus",
    "bunny_smasher",
    "a_killer",
    "carrot_crossbow",
    "festive_frying_pan_shovel",
    "carrot_on_stick_shovel",
    "watchy_snipy",
    "spiny_shooty",
    "pully_blasty",
    "chickoboom",
    "battle_grainthrowers",
    "last_cry",
    "iron_sword",
    "dragon_emitter",
    "fate_fist",
    "demon_catcher",
    "aboard_puncher",
    "deadly_tale",
    "ninja_shovel",
    "moon_shovel",
    "sword_soul_card",
    "lance_soul_card",
    "bow_soul_card",
    "vertical_grip_device",
    "siege_mode_glove",
    "one_punch_glove",
    "treasurer",
    "merchant_shovel",
    "shell_bubbler",
    "tide_bracers",
    "call_of_sirens",
    "deep_ambusher",
    "cthulhu_legacy",
    "sunken_hook_shovel",
    "atlantis_shovel",
    "mooring_anchor",
    "heavy_drill_rifle",
    "rivet_gun",
    "submarine_drone_station",
    "echo_scanner",
    "underwater_carbine",
    "project_dolphin",
    "project_rapid_flock",
    "project_marlin",
    "advanced_scout_rifle",
    "harsh_punisher",
    "manual_inferno",
    "offensive_rocket_system",
    "headhunter_pistols",
    "thunderbolt",
    "spear_of_war",
    "aphrodite_crossbow",
    "winged_revolver",
    "ferocious_poleaxe",
    "hermes_rod_shovel",
    "hydra_shovel",
    "cerberus",
    "souls_conductor",
    "triple_bite",
    "wraith_of_fire",
    "earth_trembler",
    "primal_cold",
    "boar_roar",
    "gorgon_head",
    "invincible_lion",
    "advanced_scout_rifle_l",
    "harsh_punisher_l",
    "manual_inferno_l",
    "offensive_rocket_system_l",
    "headhunter_pistols_l",
    "debugger",
    "likes_booster",
    "ban_hammer",
    "vr_blasters",
    "killer_chord",
    "invigorating_awaker",
    "total_planner",
    "money_rain",
    "render_station",
    "gun_force",
    "digital_pad",
    "graphic_shovel",
    "cheater_hunter",
    "super_fixer",
    "bugs_cleaner",
    "code_shovel",
    "good_code",
    "ambush_crocorifle",
    "bubble_splasher",
    "disguised_rifle",
    "surf_daggers_shovel",
    "sand_shovel",
    "enchanting_altar",
    "spirit_mask",
    "magical_boomerang",
    "foam_sword",
    "sand_tower_pistol",
    "watermans_rifle",
    "high_pressure_rifle",
    "sharkado",
    "shower_sprinkler",
    "star_shard",
    "solar_flare",
    "magnetic_storm",
    "MonsterHunterMechBody1",
    "ectoplasmic_grenade_launcher",
    "reversed_pistol",
    "activity_neutralizer",
    "pga_mirror_shovel",
    "dimerian_shovel",
    "goo_substance_rifle",
    "goo_substance_pistol",
    "goo_substance_scythe",
    "pga_tv",
    "pga_doll",
    "pga_gates",
    "pga_living_rifle",
    "pga_slender_touch",
    "pga_screaming_saw",
    "atomic_splitter",
    "detimerian_divider",
    "restructurer",
    "anomaly_concentrator",
    "MonsterHunterMechBody2",
    "MonsterHunterMechBody3",
    "bloq_plasma_module",
    "plasma_beast",
    "drone_station",
    "arma_shovel",
    "police_alarm_shovel",
    "max_cruelty",
    "represser",
    "fear_and_espair",
    "rude_bully",
    "laser_ninja",
    "rebel",
    "mobile_outpost",
    "outlaw_catcher",
    "fair_sheriff",
    "minigun_cyber_module",
    "med_surgery_module",
    "supply_airdrop",
    "battle_falcon",
    "super_mega_tool",
    "pneumatic_needle_rifle",
    "summon_dagger",
    "melter_shovel",
    "pg3d_flag_shovel",
    "frozen_heart",
    "eye_of_the_storm",
    "frosty_fangs",
    "combat_candy",
    "ho_ho_rocket",
    "expllosive_caramel",
    "candy_revolver",
    "elven_killer_rifle",
    "assassin_daggers",
    "farewell_volley",
    "mystic_potion",
    "siege_crossbow",
    "storm_poleaxes",
    "prophet_staff",
    "hammer_of_thor",
    "thor_shovel",
    "carved_paddle_shovel",
    "geri_n_freki",
    "sleipnir",
    "huginn",
    "deceitful_cheater",
    "cunning_flame",
    "harbinger_of_ragnarok",
    "sun_eater",
    "call_of_valhalla",
    "winged_bow",
    "war_horse",
    "glitch_machine_gun",
    "ideal_rocket_launcher",
    "noob_rifle",
    "evil_rubiks_cube",
    "super_pixel_gun",
    "ultimatum_shovel",
    "final_sentence",
    "piercer",
    "border_eraser",
    "deminic_crusher",
    "dual_beam",
    "ronin",
    "brutal_rainbow",
    "tomianom",
    "time_scythe",
    "cyber_cat_lantern",
    "laser_cat_rifle",
    "bomber_cat",
    "lab_laser_shovel",
    "evidence_hunter",
    "patrol_officer_747",
    "redneck_bazooka",
    "mayor_trophy_revolver",
    "pixel_cola_cans",
    "city_key_shovel",
    "police_baton_shovel",
    "large_machinegun",
    "tactical_pistol",
    "mammoth",
    "debts_collector",
    "godfathers_assistant",
    "black_label",
    "plan_b",
    "traitor",
    "incinerator",
    "saboteur",
    "rock_smelter",
    "tunnel_riveter",
    "complete_grinder",
    "drilling_railgun",
    "plasmatic_digger",
    "drill_shovel",
    "portalius_shovel",
    "giant_flytrap_shovel",
    "portal_rifle",
    "extracting_ray_pistol",
    "terramorphing_stone",
    "aerosaur_rifle",
    "bone_saur_sword",
    "heavy_spik_saur",
    "ritual_rifle",
    "tooth_of_fate",
    "staff_crystals_will",
    "spark_horn",
    "adventure_swords",
    "flat_rifle",
    "secret_burger",
    "charles",
    "ink_spreader",
    "eraser_crossbow",
    "pencil_spears",
    "bro_steamer",
    "sad_magnet",
    "anvil_pistol",
    "masterly_trumpet",
    "blot_axe",
    "blot_shotgun",
    "blot_cannon",
    "adventure_shovel",
    "flat_shovel",
    "mr_shovel",
    "veteran_rifle",
    "veteran_sniper_rifle",
    "veteran_rocket_system",
    "lives_harvester",
    "jet_dragon",
    "thermal_scythe",
    "simple_dimple",
    "fx_camera",
    "dance_rifle",
    "rifle_me_online",
    "virtual_orchestra",
    "sharp_chaser",
    "zap_katana",
    "cyber_lantern",
    "bro_rifle",
    "ninja_swordpad",
    "hype_yo_yo",
    "streaming_beast",
    "dislike",
    "likes_absorber",
    "bad_comment",
    "golden_button_shovel",
    "pop_it_shovel",
    "mysterious_obelisk",
    "ritual_embalmer",
    "sacred_cat_will",
    "sentinel",
    "howl_of_the_mummy",
    "punishing_light",
    "piercing_gaze_of_ra",
    "eternal_suns_wrath",
    "fair_judge",
    "black_obelisk",
    "plaguebringer",
    "scarab_shrine",
    "disturbed_sarcophagus",
    "royal_cobra_spirit",
    "pharaon_3_breath",
    "sentinel_shopeish_shovel",
    "wand_of_summoning_shovel",
    "hand_mummy_shovel",
    "block_pyramid_shovel",
    "ultrasonic_rifle",
    "electronics_burner",
    "hounds_rx03",
    "system_scorpion",
    "rumble",
    "huge_wrench_shovel",
    "shovel_spear_shovel",
    "experimental_rifle",
    "jet_spear",
    "tactical_scorcher",
    "siege_minigun",
    "thermal_mecha_knife",
    "disruptive_howitzer",
    "anti_aircraft_module",
    "engineering_saw_thrower",
    "corpuscular_revolver",
    "uranium_grenade_launcher",
    "golden_eagles",
    "wayfarer",
    "fate",
    "holographic_cards",
    "chronos_shovel",
    "mutation_cannon",
    "additional_hand_shovel",
    "hungry_flower_shovel",
    "c4_basket",
    "head_of_statue",
    "tank_turret",
    "space_parasite_dreadnought",
    "space_parasite_fighter",
    "alien_parasite_mothership",
    "bad_clown",
    "disturbing_balloons",
    "clown_chainsaw",
    "irradiated_smg",
    "mutant_fish",
    "spiky_limbs",
    "predatory_rifle",
    "mutant_weapon_one",
    "mutant_weapon_two",
    "splutter_weapon_one",
    "splutter_weapon_two",
    "jumper_weapon_one",
    "jumper_weapon_two",
    "hound_weapon_one",
    "thorn_weapon_one",
    "thorn_weapon_two",
    "supermutant_weapon_one",
    "automatic_injector",
    "antidote_missile_launcher",
    "purifying_shotgun",
    "mutant_slayer",
    "mutagen_neutralizer",
    "antidote_dropper",
    "power_gauntlet",
    "rune_buster",
    "ice_wyvern_horns",
    "runic_sentinel",
    "crystal_touch",
    "crystal_bow",
    "enchanted_crystal_of_ancients",
    "full_moon_rifle",
    "fireflies_blessing",
    "branch_of_wisdom",
    "eternal_light",
    "mirrorer",
    "realities_sign_shovel",
    "reflected_light_shovel",
    "otherworld_wanderer",
    "dark_deer_bow",
    "reflected_santa_sword",
    "combat_fireplace",
    "combat_candy_machine",
    "gift_stealer",
    "tricky_glance",
    "end_of_fairytale",
    "fairy_axe",
    "butterfly_eater",
    "class_bullet_rifle",
    "class_knight_hammer",
    "class_knight_shield",
    "class_valk_rocket",
    "class_lifeline_gun",
    "class_sara_sniper",
    "class_sara_shotgun",
    "class_saber_disk",
    "class_saber_katana",
    "class_mex_flame",
    "class_viktor_grenade",
    "handy_darts",
    "spirits_whisper",
    "makeshift_piercer",
    "battle_kusarigama",
    "temple_claws",
    "summoning_totem_shovel",
    "cloud_standard_shovel",
    "vortex_core",
    "storm_bringer",
    "clouds_disperser",
    "field_plasma_station",
    "still_working_windmill",
    "class_lifeline_healgun",
    "thunder_formula",
    "bubblegum_01",
    "tnt_thrower",
    "ak5_56",
    "disguised_weapon",
    "intelligence_swords",
    "controlled_drone_system",
    "deadly_beamer",
    "tnt_holder_shovel",
    "aliens_shredder_shovel",
    "elves_energy_crystal",
    "tricky_electrizer",
    "plague_spreader",
    "ancestors_curse",
    "moon_hunter_bow",
    "elf_heavy_crossbow",
    "lightbringer",
    "boom_bang_shovel",
    "plague_flame_shovel",
    "ice_giant_rifle",
    "moonblades",
    "eco_rifle",
    "solar_lens",
    "blacklight_pistol",
    "supernova_generator",
    "event_horizon",
    "eco_shovel",
    "crescent_moon_shovel",
    "unfriendly_bat",
    "tamagochi_revolver",
    "mad_colorer",
    "nachos_shotgun",
    "skateboard_shovel",
    "artists_tool_shovel",
    "shockorizer",
    "crescent_power",
    "odm_special_gear",
    "sharingan_vengeance",
    "doubled_quirk",
    "grenade_quirk",
    "magic_moon_wand_shovel",
    "thunder_spear_shovel",
    "guardian_spirit",
    "ghost_epee",
    "the_sorting_pistol",
    "raven_staff",
    "corrupted_speelbook",
    "additional_biting_limb",
    "pocket_potion_pot_shovel",
    "ghost_candlestick_shovel",
    "transforming_rifle",
    "monkey_pirate",
    "holographic_hook_saber",
    "navigation_shotgun",
    "three_barrels_cannon",
    "ships_drowner",
    "cosmo_underwater_mine_shovel",
    "living_specimen_shovel",
    "deadly_shark",
    "wardens_trident",
    "nets_thrower",
    "tick_tock_pistol",
    "heavy_cone_minigun",
    "starfall",
    "dreams_warden",
    "snowstorm_fury",
    "spirits_overseer",
    "s_q_dominion",
    "x_mas_vibes_setter",
    "fatal_decorator",
    "x_mas_spirits_defender",
    "nature_guards_shovel",
    "starfall_shovel",
    "harsh_dragon",
    "armor_piercing_sniper_rifle",
    "leaders_butterfly",
    "leaders_bestfriend",
    "reckoning_day_sniper_rifle",
    "reckoning_day_pistols",
    "flaming_reckoning_day",
    "festive_eliminator",
    "spirit_exorcist",
    "wealth_spreader",
    "ultimate_worship",
    "ritual_scissors",
    "dark_ritual",
    "light_devourer",
    "bloody_terror_axe",
    "sacrificial_altar",
    "hunting_signs",
    "monster_hand",
    "locator",
    "terror_spreader",
    "spring_snatcher",
    "sticky_honey_dipper",
    "chefs_bounty",
    "cloying_eliminator",
    "take_your_ice_cream",
    "pasta_grater",
    "pasta_sniper_rifle",
    "pasta_maker",
    "pg_menu",
    "space_cycler",
    "anniversary_alien_blaster",
    "anniversary_auto_peace",
    "anniversary_anti_champion",
    "anniversary_big_buddy",
    "pixel_rotator",
    "armored_cuber_power",
    "cuber_railgun",
    "secret_pg_archives",
    "block_eye",
    "honored_golden_friend",
    "classic_shovel",
    "usher",
    "special_throwing_knives",
    "springy_shotgun",
    "clockwork_guardian",
    "dark_foreteller",
    "deadly_tent",
    "playing_pistols",
    "card_sharper",
    "scary_bunny",
    "accurate_bubbler",
    "soap_hammer",
    "dangerous_miner",
    "path_lighter",
    "heavy_anchor",
    "deadly_tide",
    "abyssal_altar",
    "underwater_whip",
    "underwater_piercer",
    "underwater_overseer",
    "cyber_sai",
    "intelligent_cyber_bow",
    "deathbringer",
    "total_dominator_2",
    "evasive_dominator_4",
    "virus_spreader",
    "errors_generator",
    "revenger",
    "exchanger",
    "rebellion_spray_paints",
    "rosies_diary",
    "sharp_butterfly_rifle",
    "heart_maze",
    "stationery_friend",
    "paper_assist",
    "friendliest_pistol",
    "innocent_sniper_rifle",
    "kitten_kutie",
    "neon_tommy_gun",
    "neon_colt_1911",
    "heavy_neon_gun",
    "danger_posy",
    "spiky_mortar",
    "heavy_evidence",
    "useful_suitcase",
    "accurate_investigator",
    "new_well_pistol",
    "fps_destroyer",
    "achieve_hunter",
    "cash_gun",
    "rudolf_the_deer",
    "sooty_sniper_rifle",
    "chris_letters_shredder",
    "ninja_ice_axe",
    "cold_shinobi",
    "ice_ball_generator",
    "deadly_icing",
    "drag_sc",
    "dragoneer",
    "noble_porce",
    "dragon_x",
    "flaming_fan",
    "flaming_fury",
    "kn_arbalet",
    "scepter_and_power",
    "invig_drink",
    "bards_song",
    "gears_of_death",
    "kill_mech",
    "assas_assis",
    "souls_cycler",
    "arc_souls_dev",
    "pois_pier",
    "v_cleaner_sl",
    "rust_revol",
    "wooden_rifle",
    "forester",
    "forest_prot",
    "harm_sint",
    "high_vol_prop",
    "win_las_beam",
};

inline const char *GadgetNames[] { "gadget_armor_regeneration",
                                   "gadget_astral",
                                   "gadget_bionic_shield",
                                   "gadget_black_label",
                                   "gadget_Blizzard_generator",
                                   "gadget_christmastreeturret",
                                   "gadget_combat_spinner",
                                   "gadget_cyber_bees",
                                   "gadget_cybersamurai",
                                   "gadget_demon_stone",
                                   "gadget_denied",
                                   "gadget_disabler",
                                   "gadget_dragonwhistle",
                                   "gadget_fakebonus",
                                   "gadget_firecrackers",
                                   "gadget_firemushroom",
                                   "gadget_firework",
                                   "gadget_fraggrenade",
                                   "gadget_guardian",
                                   "gadget_hologram_projector",
                                   "gadget_jetpack",
                                   "gadget_leaderdrum",
                                   "gadget_mech",
                                   "gadget_medicalstation",
                                   "gadget_medkit",
                                   "gadget_mh_mech1",
                                   "gadget_mh_mech2",
                                   "gadget_mh_mech3",
                                   "gadget_mine",
                                   "gadget_molotov",
                                   "gadget_ninjashurickens",
                                   "gadget_nucleargrenade",
                                   "gadget_nutcracker",
                                   "gadget_pandorabox",
                                   "gadget_petbooster",
                                   "gadget_phoenix_blood",
                                   "gadget_pocket_harpoon",
                                   "gadget_reflector",
                                   "gadget_rocket_mech",
                                   "gadget_shield",
                                   "gadget_singularity",
                                   "gadget_snowman",
                                   "gadget_stealth",
                                   "gadget_sticky_turret",
                                   "gadget_stickycandy",
                                   "gadget_super_magnet",
                                   "gadget_timewatch",
                                   "gadget_turret",
                                   "gadget_x-ray_glasses",
                                   "gadget_class_bullet_medkit",
                                   "gadget_class_bullet_phonixblood",
                                   "gadget_class_knight_magnet",
                                   "gadget_class_valk_jetpack",
                                   "gadget_class_valk_cyberbees",
                                   "gadget_class_lifeline_medstation",
                                   "gadget_class_lifeline_biotiksheald",
                                   "gadget_class_sara_hook",
                                   "gadget_class_sara_xray",
                                   "gadget_class_saber_shurikens",
                                   "gadget_class_saber_reflector",
                                   "gadget_class_mex_turret",
                                   "gadget_class_mex_nucleargrenade",
                                   "gadget_class_viktor_smilemine",
                                   "gadget_class_viktor_nutcracker",
                                   "gadget_br_fraggrenade",
                                   "gadget_br_molotov",
                                   "gadget_br_mine",
                                   "gadget_hook_monster" };

static inline std::vector<std::string> PetNames = {
    "pet_cat",
    "pet_dog",
    "pet_parrot",
    "pet_rabbit",
    "pet_cat_2",
    "pet_dachshund",
    "pet_goat",
    "pet_cat_3",
    "pet_bat",
    "pet_fox",
    "pet_penguin",
    "pet_wolf",
    "pet_sheep",
    "pet_raccoon",
    "pet_husky",
    "pet_boar",
    "pet_ram",
    "pet_crab",
    "pet_owl",
    "pet_snake",
    "pet_lion",
    "pet_panda",
    "pet_red_panda",
    "pet_tukan",
    "pet_meerkat",
    "pet_robo_dog",
    "pet_porcupine",
    "pet_zombiecat",
    "pet_eagle",
    "pet_deer",
    "pet_polarbear",
    "pet_monkey",
    "pet_alien_cat",
    "pet_bear",
    "pet_hyena",
    "pet_kangaroo",
    "pet_skunk",
    "pet_ostrich",
    "pet_pterodactyl",
    "pet_dinosaur",
    "pet_arnold_3000",
    "pet_chicken",
    "pet_paradehorse",
    "pet_rhino",
    "pet_tiger",
    "pet_panther",
    "pet_horse",
    "pet_unicorn",
    "pet_phoenix",
    "pet_magical_dragon",
    "pet_griffin",
    "pet_eaglespirit",
    "pet_mammoth",
    "pet_sabertooth_tiger",
    "pet_raven",
    "pet_trex",
    "pet_cyberphoenix",
    "pet_blocston_dogmatics",
    "pet_turkey",
    "pet_armadillo",
    "pet_griffin_owl",
    "pet_squirrel",
    "pet_tactical_ferret",
    "pet_stone_elemental",
    "pet_fighting_turtle",
    "pet_knitted_pony",
    "pet_stone",
    "pet_horse_figure",
    "pet_lucky_duck",
    "pet_green_novice",
    "pet_headbug",
    "pet_chick01",
    "pet_pocket_demon",
    "pet_flappy_fish",
    "pet_zazou",
    "pet_pga_statue",
    "pet_vacuum_helpbro_2000",
    "pet_ice_dragon_egg",
    "pet_combat_robb_e",
    "pet_small_floppa",
    "pet_sacred_scarab",
    "pet_mecha_cat",
    "pet_zombie_head",
    "pet_support_piglet",
    "pet_firefly_cat",
    "pet_elementals_helper",
    "pet_tankmouse",
    "pet_backwater_dweller",
    "pet_shiny_companion",
    "pet_8_bit_boi",
    "pet_blue_buddy",
    "pet_wise_owl",
    "pet_stingray_3000",
    "pet_bullfinch_the_giver",
    "pet_festive_black_rabbit",
    "pet_servants_right_hand",
    "pet_ice_cream_cup",
    "pet_anniversary_kitty",
    "pet_capy",
    "pet_modified_assistant",
    "pet_cheering_up_cookie",
};

struct ArmorData {
    int category;
    std::string id;
};

static inline std::vector<ArmorData> ArmorNames = {
    { 9, "mask_doctor_plague" },
    { 9, "mask_anime_glasses" },
    { 9, "mask_smart_bullet_bazooka" },
    { 9, "mask_stop_posting_hepi" },
    { 7, "armor_black_dragon" },
    { 7, "armor_clan_golden" },
    { 7, "armor_clan_steel" },
    { 7, "armor_clan_wooden" },
    { 7, "armor_crystal_clan" },
    { 7, "armor_dope_windcheater" },
    { 7, "armor_inflatable" },
    { 7, "armor_stardust" },
    { 7, "armor_ultimate_defense" },
    { 7, "developer_armor" },
    { 7, "starter_pack_armor" },
    { 9, "cape_BloodyDemon" },
    { 9, "cape_RoyalKnight" },
    { 9, "cape_SkeletonLord" },
    { 9, "cape_Archimage" },
    { 9, "cape_boss" },
    { 9, "cape_EliteCrafter" },
    { 9, "cape_of_loneliness" },
    { 9, "cape_Custom" },
    { 9, "cape_vaneuvering_module" },
    { 9, "cape_pg_hero_cape" },
    { 9, "cape_fun_fair_cape" },
    { 6, "hat_Headphones" },
    { 6, "hat_ManiacMask" },
    { 6, "hat_KingsCrown" },
    { 6, "hat_Samurai" },
    { 6, "hat_DiamondHelmet" },
    { 6, "hat_SeriousManHat" },
    { 6, "hat_AlmazHelmet" },
    { 6, "hat_ArmyHelmet" },
    { 6, "hat_GoldHelmet" },
    { 6, "hat_SteelHelmet" },
    { 6, "league1_hat_hitman" },
    { 6, "league2_hat_cowboyhat" },
    { 6, "league3_hat_afro" },
    { 6, "league4_hat_mushroom" },
    { 6, "league5_hat_brain" },
    { 6, "league6_hat_tiara" },
    { 6, "hat_Army_1" },
    { 6, "hat_Royal_1" },
    { 6, "hat_Almaz_1" },
    { 6, "hat_Steel_1" },
    { 6, "hat_Army_2" },
    { 6, "hat_Royal_2" },
    { 6, "hat_Almaz_2" },
    { 6, "hat_Steel_2" },
    { 6, "hat_Army_3" },
    { 6, "hat_Royal_3" },
    { 6, "hat_Almaz_3" },
    { 6, "hat_Steel_3" },
    { 6, "hat_Army_4" },
    { 6, "hat_Royal_4" },
    { 6, "hat_Almaz_4" },
    { 6, "hat_Steel_4" },
    { 6, "hat_Rubin_1" },
    { 6, "hat_Rubin_2" },
    { 6, "hat_Rubin_3" },
    { 10, "boots_black" },
    { 10, "boots_blue" },
    { 10, "boots_gray" },
    { 10, "boots_green" },
    { 10, "boots_red" },
    { 10, "boots_tabi" },
    { 10, "boots_natural" },
    { 10, "boots_black_dragon" },
    { 6, "hat_black_dragon" },
    { 12, "mask_black_dragon" },
    { 7, "Armor_Army_1" },
    { 9, "StormTrooperCape_Up1" },
    { 9, "StormTrooperCape_Up2" },
    { 9, "HitmanCape_Up1" },
    { 9, "HitmanCape_Up2" },
    { 9, "BerserkCape_Up1" },
    { 9, "BerserkCape_Up2" },
    { 9, "SniperCape_Up1" },
    { 9, "SniperCape_Up2" },
    { 9, "cape_Engineer" },
    { 9, "cape_Engineer_Up1" },
    { 9, "cape_Engineer_Up2" },
    { 9, "cape_of_intelligence" },
    { 9, "cape_cloak_of_night" },
    { 9, "DemolitionCape_Up1" },
    { 9, "DemolitionCape_Up2" },
    { 6, "hat_Headphones_Up1" },
    { 6, "hat_Headphones_Up2" },
    { 6, "hat_ManiacMask_Up1" },
    { 6, "hat_ManiacMask_Up2" },
    { 6, "hat_KingsCrown_Up1" },
    { 6, "hat_KingsCrown_Up2" },
    { 6, "hat_Samurai_Up1" },
    { 6, "hat_Samurai_Up2" },
    { 6, "hat_DiamondHelmet_Up1" },
    { 6, "hat_DiamondHelmet_Up2" },
    { 6, "hat_SeriousManHat_Up1" },
    { 6, "hat_SeriousManHat_Up2" },
    { 6, "hat_space_delivery" },
    { 10, "StormTrooperBoots_Up1" },
    { 10, "StormTrooperBoots_Up2" },
    { 10, "HitmanBoots_Up1" },
    { 10, "HitmanBoots_Up2" },
    { 10, "BerserkBoots_Up1" },
    { 10, "BerserkBoots_Up2" },
    { 10, "SniperBoots_Up1" },
    { 10, "SniperBoots_Up2" },
    { 10, "DemolitionBoots_Up1" },
    { 10, "DemolitionBoots_Up2" },
    { 10, "EngineerBoots" },
    { 10, "EngineerBoots_Up1" },
    { 10, "EngineerBoots_Up2" },
    { 10, "boots_roller_skates" },
    { 10, "boots_space_delivery" },
    { 6, "hat_Adamant_3" },
    { 6, "hat_Adamant_Const_1" },
    { 6, "hat_Adamant_Const_2" },
    { 6, "hat_Adamant_Const_3" },
    { 12, "mask_sniper" },
    { 12, "mask_sniper_up1" },
    { 12, "mask_sniper_up2" },
    { 12, "mask_demolition" },
    { 12, "mask_demolition_up1" },
    { 12, "mask_demolition_up2" },
    { 12, "mask_berserk" },
    { 12, "mask_berserk_up1" },
    { 12, "mask_berserk_up2" },
    { 12, "mask_trooper" },
    { 12, "mask_trooper_up1" },
    { 12, "mask_trooper_up2" },
    { 12, "mask_hitman_1" },
    { 12, "mask_hitman_1_up1" },
    { 12, "mask_hitman_1_up2" },
    { 12, "mask_natural" },
    { 12, "mask_engineer" },
    { 12, "mask_engineer_up1" },
    { 12, "mask_engineer_up2" },
    { 12, "boots_cyber_santa" },
    { 12, "boots_cyber_santa_Up1" },
    { 12, "boots_cyber_santa_Up2" },
    { 12, "mask_cyber_santa" },
    { 12, "mask_cyber_santa_Up1" },
    { 12, "mask_cyber_santa_Up2" },
    { 6, "hat_cyber_santa" },
    { 6, "hat_cyber_santa_Up1" },
    { 6, "hat_cyber_santa_Up2" },
    { 6, "hat_exoskeleton_pilot_avatar" },
    { 6, "hat_exoskeleton_pilot_avatar_up1" },
    { 6, "hat_exoskeleton_pilot_avatar_up2" },
    { 12, "mask_exoskeleton_pilot_avatar" },
    { 12, "mask_exoskeleton_pilot_avatar_up1" },
    { 12, "mask_exoskeleton_pilot_avatar_up2" },
    { 10, "boots_exoskeleton_pilot_avatar" },
    { 10, "boots_exoskeleton_pilot_avatar_up1" },
    { 10, "boots_exoskeleton_pilot_avatar_up2" },
    { 6, "hat_halloween" },
    { 6, "hat_halloween_up1" },
    { 6, "hat_halloween_up2" },
    { 12, "mask_halloween" },
    { 12, "mask_halloween_up1" },
    { 12, "mask_halloween_up2" },
    { 10, "boots_halloween" },
    { 10, "boots_halloween_up1" },
    { 10, "boots_halloween_up2" },
    { 6, "hat_piligrim" },
    { 6, "hat_piligrim_up1" },
    { 6, "hat_piligrim_up2" },
    { 12, "mask_turkey_piligrim" },
    { 12, "mask_turkey_piligrim_up1" },
    { 12, "mask_turkey_piligrim_up2" },
    { 10, "boots_piligrim" },
    { 10, "boots_piligrim_up1" },
    { 10, "boots_piligrim_up2" },
    { 12, "mask_medical_mask" },
    { 12, "mask_medical_mask_up1" },
    { 12, "mask_medical_mask_up2" },
    { 6, "hat_chest" },
    { 6, "hat_high_end_earphones" },
    { 10, "boots_ultimate_defense" },
    { 9, "cape_ultimate_defense" },
    { 12, "mask_ultimate_defense" },
    { 10, "boots_magic_gift" },
    { 9, "cape_magic_gift" },
    { 6, "hat_magic_gift" },
    { 9, "cape_gifts" },
    { 9, "cape_loyalty" },
    { 9, "cape_screen" },
    { 10, "boots_stardust" },
    { 6, "hat_stardust" },
};